name: Deploy ADF to Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Log in to Azure
      uses: azure/login@v1

    - name: Deploy ADF ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        ClientID: ${{ secrets.AZURE_CLIENT}}
        TenantID: ${{ secrets.AZURE_TENANT}}
        Secrets: ${{ secrets.AZURE_SECRETS}}
        
        resourceGroupName: rg-test
        template: ./dev-adf-vikash/ARMTemplateForFactory.json
        parameters: ./dev-adf-vikash/ARMTemplateParametersForFactory.json
        deploymentName: adf-deployment-${{ github.run_number }}
        deploymentMode: Incremental
