
# .github/workflows/release-adf-pipeline.yml
# This workflow handles both Test and Production deployments of Azure Data Factory.
# It triggers when a new GitHub Release is published.

name: ADF CI/CD Release Pipeline

on:
  release:
    types: [published] # Triggers the workflow when a new release is published

env:
  # General Environment Variables - ADJUST THESE TO YOUR ACTUAL ADF NAMES AND RESOURCE GROUPS
  # These are common variables used across both test and prod jobs
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # Common subscription ID, or separate secrets if subscriptions differ
  RELEASE_TAG: ${{ github.ref_name }}                          # The name of the published release tag (e.g., v1.0.0)
  ADF_DEV_SUBFOLDER_NAME: "dev-adf-vikash"                    # The name of your DEV ADF instance (where templates were generated)

permissions:
  id-token: write # Required for OpenID Connect (OIDC) authentication
  contents: read  # Required to checkout the repository code

jobs:
  deploy-test:
    name: Deploy to TEST Environment
    runs-on: ubuntu-latest
    # This job has no 'needs' dependency, making it the entry point for the workflow.
    environment: test # Links to your 'test' GitHub environment for secrets and protection rules

    env:
      # Environment variables specific to the TEST deployment
      ADF_RESOURCE_GROUP_TEST: 'rg-test'       # Your Test ADF Resource Group
      ADF_NAME_TEST: 'test-adf-vikash'            # Your Test ADF Name (The ACTUAL name of your Test ADF instance)

    steps:
    - name: Checkout adf_publish branch for ARM templates
      uses: actions/checkout@v4
      with:
        ref: adf_publish       # Specifies the branch where your ADF publishes its ARM templates
        path: adf_publish_repo # Clones the branch content into this directory

    - name: Prepare ARM Template Parameters for Test Environment
      run: |
        # Define paths to the base parameters file
        BASE_PARAMS_FILE="${{ github.workspace }}/adf_publish_repo/${{ env.ADF_DEV_SUBFOLDER_NAME }}/ARMTemplateParametersForFactory.json"
        TEMP_PARAMS_FILE="${{ github.workspace }}/adf_publish_repo/${{ env.ADF_DEV_SUBFOLDER_NAME }}/ARMTemplateParametersForFactory.temp.json"
        
        # Install jq (if not already present on the runner) for JSON manipulation
        sudo apt-get update && sudo apt-get install -y jq
        
        # Modify the 'factoryName' parameter in the ARMTemplateParametersForFactory.json file.
        # This is crucial to ensure the deployment targets the correct ADF instance in the Test environment.
        jq --arg new_adf_name "${{ env.ADF_NAME_TEST }}" \
           '.parameters.factoryName.value = $new_adf_name' \
           "$BASE_PARAMS_FILE" > "$TEMP_PARAMS_FILE"
        
        # Overwrite the original parameters file with the modified one.
        mv "$TEMP_PARAMS_FILE" "$BASE_PARAMS_FILE"
        echo "Modified ARMTemplateParametersForFactory.json for Test environment. New ADF name: ${{ env.ADF_NAME_TEST }}"
      
    - name: Azure Login (Test)
      uses: azure/login@v1 # Uses the Azure login action for OIDC authentication
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID_TEST }}   # Client ID of your Azure AD App Registration for Test
        tenant-id: ${{ secrets.AZURE_TENANT_ID_TEST }}   # Your Azure Tenant ID for Test
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }} # Target Azure Subscription ID for deployment

    - name: Deploy Azure Data Factory (Test)
      run: |
        # Define paths to the ARM template and parameters file
        ADF_ARM_TEMPLATE_PATH="${{ github.workspace }}/adf_publish_repo/${{ env.ADF_DEV_SUBFOLDER_NAME }}/ARMTemplateForFactory.json"
        ADF_ARM_PARAMETERS_PATH="${{ github.workspace }}/adf_publish_repo/${{ env.ADF_DEV_SUBFOLDER_NAME }}/ARMTemplateParametersForFactory.json" 
        
        echo "Attempting to deploy ARM template from: $ADF_ARM_TEMPLATE_PATH"
        echo "Starting incremental deployment to Test ADF: ${{ env.ADF_NAME_TEST }} for release ${{ env.RELEASE_TAG }}"
        
        # Execute the Azure CLI command to deploy the ARM template
        az deployment group create \
          --resource-group ${{ env.ADF_RESOURCE_GROUP_TEST }} \
          --template-file "$ADF_ARM_TEMPLATE_PATH" \
          --parameters "$ADF_ARM_PARAMETERS_PATH" \
          --name "ADF-Test-Release-${{ env.RELEASE_TAG }}-${{ github.run_number }}" \
          --mode Incremental 

    - name: Post-Deployment Steps (Test)
      run: |
        echo "Test deployment for release ${{ env.RELEASE_TAG }} completed successfully!"
    
    # You might want to upload artifacts from Test here if needed for Prod validation
    - name: Upload Test Deployment Artifacts (Optional)
      uses: actions/upload-artifact@v4 
      with:
        name: adf-arm-templates-test-${{ env.RELEASE_TAG }} # Unique name for the artifact
        path: adf_publish_repo/${{ env.ADF_DEV_SUBFOLDER_NAME }}/ # Path to the deployed template files
        retention-days: 7                                  # How long to retain the artifact

  deploy-prod:
    name: Deploy to PROD Environment
    runs-on: ubuntu-latest
    needs: deploy-test # This ensures the 'deploy-test' job completes successfully first
    environment: prod  # Links to your 'prod' GitHub environment for secrets and protection rules

    env:
      # Environment variables specific to the PROD deployment
      ADF_RESOURCE_GROUP_PROD: 'rg-prod'       # Your Prod ADF Resource Group (e.g., 'your-prod-rg')
      ADF_NAME_PROD: 'prod-adf-vikash'            # Your Prod ADF Name (The ACTUAL name of your Prod ADF instance) (e.g., 'your-prod-adf')

    steps:
    - name: Checkout adf_publish branch for ARM templates
      uses: actions/checkout@v4
      with:
        ref: adf_publish       # Specifies the branch where your ADF publishes its ARM templates
        path: adf_publish_repo # Clones the branch content into this directory

    - name: Prepare ARM Template Parameters for Prod Environment
      run: |
        # Define paths to the base parameters file
        BASE_PARAMS_FILE="${{ github.workspace }}/adf_publish_repo/${{ env.ADF_DEV_SUBFOLDER_NAME }}/ARMTemplateParametersForFactory.json"
        TEMP_PARAMS_FILE="${{ github.workspace }}/adf_publish_repo/${{ env.ADF_DEV_SUBFOLDER_NAME }}/ARMTemplateParametersForFactory.temp.json"
        
        # Install jq (if not already present on the runner) for JSON manipulation
        sudo apt-get update && sudo apt-get install -y jq
        
        # Modify the 'factoryName' parameter for the Prod environment.
        jq --arg new_adf_name "${{ env.ADF_NAME_PROD }}" \
           '.parameters.factoryName.value = $new_adf_name' \
           "$BASE_PARAMS_FILE" > "$TEMP_PARAMS_FILE"
        
        # Overwrite the original parameters file with the modified one.
        mv "$TEMP_PARAMS_FILE" "$BASE_PARAMS_FILE"
        echo "Modified ARMTemplateParametersForFactory.json for Prod environment. New ADF name: ${{ env.ADF_NAME_PROD }}"
      
    - name: Azure Login (Prod)
      uses: azure/login@v1 # Uses the Azure login action for OIDC authentication
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID_PROD }}   # Client ID of your Azure AD App Registration for Prod
        tenant-id: ${{ secrets.AZURE_TENANT_ID_PROD }}   # Your Azure Tenant ID for Prod
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }} # Target Azure Subscription ID for deployment

    - name: Deploy Azure Data Factory (Prod)
      run: |
        # Define paths to the ARM template and parameters file
        ADF_ARM_TEMPLATE_PATH="${{ github.workspace }}/adf_publish_repo/${{ env.ADF_DEV_SUBFOLDER_NAME }}/ARMTemplateForFactory.json"
        ADF_ARM_PARAMETERS_PATH="${{ github.workspace }}/adf_publish_repo/${{ env.ADF_DEV_SUBFOLDER_NAME }}/ARMTemplateParametersForFactory.json" 
        
        echo "Attempting to deploy ARM template from: $ADF_ARM_TEMPLATE_PATH"
        echo "Starting incremental deployment to Prod ADF: ${{ env.ADF_NAME_PROD }} for release ${{ env.RELEASE_TAG }}"
        
        # Execute the Azure CLI command to deploy the ARM template
        az deployment group create \
          --resource-group ${{ env.ADF_RESOURCE_GROUP_PROD }} \
          --template-file "$ADF_ARM_TEMPLATE_PATH" \
          --parameters "$ADF_ARM_PARAMETERS_PATH" \
          --name "ADF-Prod-Release-${{ env.RELEASE_TAG }}-${{ github.run_number }}" \
          --mode Incremental 

    - name: Post-Deployment Steps (Prod)
      run: |
        echo "Prod deployment for release ${{ env.RELEASE_TAG }} completed successfully!"
    
    - name: Upload Prod Deployment Artifacts (Optional)
      uses: actions/upload-artifact@v4 
      with:
        name: adf-arm-templates-prod-${{ env.RELEASE_TAG }} 
        path: adf_publish_repo/${{ env.ADF_DEV_SUBFOLDER_NAME }}/
        retention-days: 7
