name: Deploy ADF to Test and Prod
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-test:
    name: Deploy to TEST
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the ADF Publish Branch
      - name: Checkout ADF Publish Branch
        uses: actions/checkout@v4
        with:
          ref: adf_publish # This is crucial! Checkout the branch where ADF publishes its ARM templates
          path: adf_published_artifacts # This will put the content into a folder named adf_published_artifacts

      # Debugging step (keep this for now)
      - name: Debug - List files in adf_published_artifacts
        run: |
          echo "Listing contents of: ${{ github.workspace }}/adf_published_artifacts"
          ls -R "${{ github.workspace }}/adf_published_artifacts" || echo "adf_published_artifacts not found or empty"
          echo "Listing contents of: ${{ github.workspace }}/adf_published_artifacts/dev-adf-vikash"
          ls -R "${{ github.workspace }}/adf_published_artifacts/dev-adf-vikash" || echo "dev-adf-vikash not found or empty"
        continue-on-error: true

      - name: Login to Azure (TEST)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}

      - name: Prepare ARM Template Parameters for Test Environment
        id: prepare_params_test
        run: |
          ADF_SUBFOLDER_NAME="dev-adf-vikash" # This is usually the name of your Data Factory instance
          # Adjust path based on the `path` specified in the checkout step
          ADF_TEMPLATE_PATH="${{ github.workspace }}/adf_published_artifacts/${ADF_SUBFOLDER_NAME}/ARMTemplateForFactory.json"
          ADF_PARAMETERS_PATH="${{ github.workspace }}/adf_published_artifacts/${ADF_SUBFOLDER_NAME}/ARMTemplateParametersForFactory.json"

          # Validate existence of files before setting outputs (optional, but good practice)
          if [ ! -f "$ADF_TEMPLATE_PATH" ]; then
            echo "Error: ARM template not found at $ADF_TEMPLATE_PATH"
            exit 1
          fi
          if [ ! -f "$ADF_PARAMETERS_PATH" ]; then
            echo "Error: ARM parameters file not found at $ADF_PARAMETERS_PATH"
            exit 1
          fi

          echo "::set-output name=template_path::$ADF_TEMPLATE_PATH"
          echo "::set-output name=parameters_path::$ADF_PARAMETERS_PATH"

      - name: Deploy ADF ARM Template to TEST
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS_TEST).subscriptionId }}
          resourceGroupName: ${{ secrets.ADF_RESOURCE_GROUP_TEST }}
          template: ${{ steps.prepare_params_test.outputs.template_path }}
          parameters: ${{ steps.prepare_params_test.outputs.parameters_path }}
          deploymentMode: Incremental # Or Complete, depending on your needs. Incremental is safer.
          deploymentName: adf-deploy-test
          scope: resourcegroup
          failOnStdErr: false

  deploy-prod:
    name: Deploy to PROD
    needs: deploy-test
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the ADF Publish Branch for PROD job as well
      - name: Checkout ADF Publish Branch
        uses: actions/checkout@v4
        with:
          ref: adf_publish # Crucial for PROD as well
          path: adf_published_artifacts

      # Debugging step (keep this for now)
      - name: Debug - List files in adf_published_artifacts (PROD)
        run: |
          echo "Listing contents of: ${{ github.workspace }}/adf_published_artifacts"
          ls -R "${{ github.workspace }}/adf_published_artifacts" || echo "adf_published_artifacts not found or empty"
          echo "Listing contents of: ${{ github.workspace }}/adf_published_artifacts/dev-adf-vikash"
          ls -R "${{ github.workspace }}/adf_published_artifacts/dev-adf-vikash" || echo "dev-adf-vikash not found or empty"
        continue-on-error: true

      - name: Login to Azure (PROD)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      - name: Prepare ARM Template Parameters for Prod Environment
        id: prepare_params_prod
        run: |
          ADF_SUBFOLDER_NAME="dev-adf-vikash"
          ADF_TEMPLATE_PATH="${{ github.workspace }}/adf_published_artifacts/${ADF_SUBFOLDER_NAME}/ARMTemplateForFactory.json"
          ADF_PARAMETERS_PATH="${{ github.workspace }}/adf_published_artifacts/${ADF_SUBFOLDER_NAME}/ARMTemplateParametersForFactory.json"

          if [ ! -f "$ADF_TEMPLATE_PATH" ]; then
            echo "Error: ARM template not found at $ADF_TEMPLATE_PATH"
            exit 1
          fi
          if [ ! -f "$ADF_PARAMETERS_PATH" ]; then
            echo "Error: ARM parameters file not found at $ADF_PARAMETERS_PATH"
            exit 1
          fi

          # ... (your logic to modify PROD parameters if needed) ...

          echo "::set-output name=template_path::$ADF_TEMPLATE_PATH"
          echo "::set-output name=parameters_path::$ADF_PARAMETERS_PATH"

      - name: Deploy ADF ARM Template to PROD
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS_PROD).subscriptionId }}
          resourceGroupName: ${{ secrets.ADF_RESOURCE_GROUP_PROD }}
          template: ${{ steps.prepare_params_prod.outputs.template_path }}
          parameters: ${{ steps.prepare_params_prod.outputs.parameters_path }}
          deploymentMode: Incremental # Or Complete
          deploymentName: adf-deploy-prod
          scope: resourcegroup
          failOnStdErr: false
