name: Deploy ADF to Test and Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-test:
    name: Deploy to TEST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure (TEST)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_TEST_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TEST_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_TEST_CLIENT_SECRET }}

      - name: Deploy ADF ARM Template to TEST
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.ADF_RESOURCE_GROUP_TEST }}
          template: ./dev-adf-vikash/ARMTemplateForFactory.json
          parameters: ./dev-adf-vikash/ARMTemplateParametersForFactory.json
          deploymentName: adf-deploy-test
          scope: resourcegroup
          failOnStdErr: false

  deploy-prod:
    name: Deploy to PROD
    needs: deploy-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure (PROD)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_PROD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_PROD_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_PROD_CLIENT_SECRET }}

      - name: Deploy ADF ARM Template to PROD
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.ADF_RESOURCE_GROUP_PROD }}
          template: ./ARMTemplateForFactory/ARMTemplate.json
          parameters: ./ARMTemplateForFactory/ARMTemplateParametersForFactory.json
          deploymentName: adf-deploy-prod
          scope: resourcegroup
          failOnStdErr: false
