name: Deploy ADF to Test and Prod
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-test:
    name: Deploy to TEST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure (TEST)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}

      - name: Prepare ARM Template Parameters for Test Environment
        id: prepare_params_test # Add an ID to reference outputs
        run: |
          ADF_SUBFOLDER_NAME="dev-adf-vikash" # The name of your DEV ADF instance (where templates were generated)
          # Assuming the generated ARM template is ARMTemplateForFactory.json and parameters are ARMTemplateParametersForFactory.json
          ADF_TEMPLATE_PATH="${{ github.workspace }}/adf_publish_repo/${ADF_SUBFOLDER_NAME}/ARMTemplateForFactory.json"
          ADF_PARAMETERS_PATH="${{ github.workspace }}/adf_publish_repo/${ADF_SUBFOLDER_NAME}/ARMTemplateParametersForFactory.json"
          
          # You might want to modify the parameters file for the specific environment (TEST/PROD) here.
          # For example, if you have environment-specific values for certain parameters:
          # cat "$ADF_PARAMETERS_PATH" | jq '.parameters.paramName.value = "testValue"' > "$ADF_PARAMETERS_PATH.temp"
          # mv "$ADF_PARAMETERS_PATH.temp" "$ADF_PARAMETERS_PATH"

          echo "::set-output name=template_path::$ADF_TEMPLATE_PATH"
          echo "::set-output name=parameters_path::$ADF_PARAMETERS_PATH"
          echo "Deployment name will be adf-deploy-test" # This is just a log, not an output for the next step

      - name: Deploy ADF ARM Template to TEST
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS_TEST).subscriptionId }}
          resourceGroupName: ${{ secrets.ADF_RESOURCE_GROUP_TEST }}
          template: ${{ steps.prepare_params_test.outputs.template_path }} # Use the output from the previous step
          parameters: ${{ steps.prepare_params_test.outputs.parameters_path }} # Use the output from the previous step
          deploymentName: adf-deploy-test # This should be a direct input to the action
          scope: resourcegroup # This should be a direct input to the action
          failOnStdErr: false # This should be a direct input to the action

  deploy-prod:
    name: Deploy to PROD
    needs: deploy-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure (PROD)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      - name: Prepare ARM Template Parameters for Prod Environment
        id: prepare_params_prod # Add an ID to reference outputs
        run: |
          ADF_SUBFOLDER_NAME="dev-adf-vikash" # The name of your DEV ADF instance (where templates were generated)
          ADF_TEMPLATE_PATH="${{ github.workspace }}/adf_publish_repo/${ADF_SUBFOLDER_NAME}/ARMTemplateForFactory.json"
          ADF_PARAMETERS_PATH="${{ github.workspace }}/adf_publish_repo/${ADF_SUBFOLDER_NAME}/ARMTemplateParametersForFactory.json"
          
          # Adjust parameters for PROD environment if necessary
          # For example, if you have environment-specific values for certain parameters:
          # cat "$ADF_PARAMETERS_PATH" | jq '.parameters.paramName.value = "prodValue"' > "$ADF_PARAMETERS_PATH.temp"
          # mv "$ADF_PARAMETERS_PATH.temp" "$ADF_PARAMETERS_PATH"

          echo "::set-output name=template_path::$ADF_TEMPLATE_PATH"
          echo "::set-output name=parameters_path::$ADF_PARAMETERS_PATH"
          echo "Deployment name will be adf-deploy-prod"

      - name: Deploy ADF ARM Template to PROD
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS_PROD).subscriptionId }}
          resourceGroupName: ${{ secrets.ADF_RESOURCE_GROUP_PROD }}
          template: ${{ steps.prepare_params_prod.outputs.template_path }}
          parameters: ${{ steps.prepare_params_prod.outputs.parameters_path }}
          deploymentName: adf-deploy-prod
          scope: resourcegroup
          failOnStdErr: false
