name: Deploy ADF to Test and Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-test:
    name: Deploy to TEST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure (TEST)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}

      - name: Deploy ADF ARM Template to TEST
        uses: azure/arm-deploy@v1
        with:
    subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS_TEST).subscriptionId }}
    resourceGroupName: ${{ secrets.ADF_RESOURCE_GROUP_TEST }}
    template: adf_publish_repo/dev-adf-vikash/ARMTemplateForFactory.json
    parameters: adf_publish_repo/dev-adf-vikash/ARMTemplateParametersForFactory.json
    deploymentName: adf-deploy-test
    scope: resourcegroup
  deploy-prod:
    name: Deploy to PROD
    needs: deploy-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
      ref: adf_publish

    - name: Login to Azure (PROD)
  uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      - name: Deploy ADF ARM Template to PROD
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS_PROD).subscriptionId }}
          resourceGroupName: ${{ secrets.ADF_RESOURCE_GROUP_PROD }}
          ref: adf_publish
          path: adf_publish_repo

      - name: Deploy ADF ARM Template to Prod
        uses: azure/arm-deploy@v1
        with:
    subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS_TEST).subscriptionId }}
    resourceGroupName: ${{ secrets.ADF_RESOURCE_GROUP_TEST }}
    template: adf_publish_repo/dev-adf-vikash/ARMTemplateForFactory.json
    parameters: adf_publish_repo/dev-adf-vikash/ARMTemplateParametersForFactory.json
    deploymentName: adf-deploy-test
    scope: resourcegroup
